version: "3.4"
services:
  service-a:
    build: ./service-A
    container_name: 'service-a'
    environment:
      - spring_profiles_active=docker
      - SERVICE_B_HOST=host.docker.internal
    ports:
      - 8081:8081
  service-b:
    build: ./service-B
    container_name: 'service-b'
    environment:
      - spring_profiles_active=docker
    ports:
      - 8082:8082