server:
  port : 8081
spring:
  profiles:
    active: local
  application:
    name: service-A
serviceb:
  url: http://localhost:8082
  path:
    greet: /greet/{id}
feign:
  client:
    config:
      serviceb:
        connectTimeout: 3000
        readTimeout: 3000
resilience4j.circuitbreaker:
  instances:
    serviceB:
      registerHealthIndicator: true
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
